projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
      - src/app/API.service.ts
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: 2c2z2xneozbzrpjthbtjlhje4y
        frontend: javascript
        framework: angular
        amplifyJsLibraryVersion: 6
        maxDepth: 2
